# name: Build and Push to ECR

# on:
#   push:
#     branches:
#       - main

# env:
#   AWS_REGION: us-west-1
#   ECR_REPO: 631415161171.dkr.ecr.us-west-1.amazonaws.com/docker-image-scan-poc

# jobs:
#   build_and_push:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ env.AWS_REGION }}

#       - name: Build Docker image
#         run: docker build -t python:latest .

#       - name: Login to Amazon ECR
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v1

#       - name: Tag Docker image
#         run: docker tag python:latest ${{ env.ECR_REPO }}:latest

#       - name: Push Docker image to ECR
#         run: docker push ${{ env.ECR_REPO }}:latest
