name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and tag Docker image
        run: |
          docker buildx create --use
          docker buildx build --push --tag docker-image .
        env:
          AWS_REGION: us-west-1
          ECR_REPOSITORY: docker-image-scan-poc

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Enable image scanning in ECR
        run: |
          aws ecr put-image-scanning-configuration --repository-name ${{ env.ECR_REPOSITORY }} --image-scanning-configuration scanOnPush=true

      - name: Log in to ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin 631415161171.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Tag and push Docker image to ECR
        run: |
          docker tag your-image-name:latest 631415161171.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest
          docker push 631415161171.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest
